"""add user model and link to emails

Revision ID: 3ccb8608c36c
Revises: d4220cde3c32
Create Date: 2026-03-25 11:48:31.978897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccb8608c36c'
down_revision = 'd4220cde3c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_analyzed_email_email_id'), ['email_id'])
        batch_op.create_foreign_key(batch_op.f('fk_analyzed_email_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_email', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_analyzed_email_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_analyzed_email_email_id'), type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
