"""consolidate databases

Revision ID: d4220cde3c32
Revises: e3769e56dcb6
Create Date: 2026-03-25 10:39:43.772411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4220cde3c32'
down_revision = 'e3769e56dcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('risk_factors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('safety_score', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reasoning', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_email', schema=None) as batch_op:
        batch_op.drop_column('reasoning')
        batch_op.drop_column('safety_score')
        batch_op.drop_column('risk_factors')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
