"""Add sender and subject columns to AnalyzedEmail

Revision ID: d8a8cf1afc2e
Revises: dcb506e70a42
Create Date: 2025-10-18 22:22:58.399063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a8cf1afc2e'
down_revision = 'dcb506e70a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_email', schema=None) as batch_op:
        batch_op.drop_column('subject')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
