"""initial migration

Revision ID: dcb506e70a42
Revises: 
Create Date: 2025-10-18 19:35:19.009200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb506e70a42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzed_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyzed_email')
    # ### end Alembic commands ###
