"""Add content column to AnalyzedEmail

Revision ID: e3769e56dcb6
Revises: d8a8cf1afc2e
Create Date: 2025-10-26 12:31:32.369221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3769e56dcb6'
down_revision = 'd8a8cf1afc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzed_email', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
